// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Producto struct {
	ID          int32
	Nombre      string
	Descripcion sql.NullString
	Precio      string
	Stock       int32
}
