// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createProducto = `-- name: CreateProducto :one
INSERT INTO productos (nombre, descripcion, precio, stock)
VALUES ($1, $2, $3, $4)
RETURNING id, nombre, descripcion, precio, stock
`

type CreateProductoParams struct {
	Nombre      string
	Descripcion sql.NullString
	Precio      string
	Stock       int32
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, createProducto,
		arg.Nombre,
		arg.Descripcion,
		arg.Precio,
		arg.Stock,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Precio,
		&i.Stock,
	)
	return i, err
}

const deleteProducto = `-- name: DeleteProducto :exec
DELETE FROM productos WHERE id = $1
`

func (q *Queries) DeleteProducto(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProducto, id)
	return err
}

const getProductoByID = `-- name: GetProductoByID :one
SELECT id, nombre, descripcion, precio, stock FROM productos WHERE id = $1
`

func (q *Queries) GetProductoByID(ctx context.Context, id int32) (Producto, error) {
	row := q.db.QueryRowContext(ctx, getProductoByID, id)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Precio,
		&i.Stock,
	)
	return i, err
}

const listProductos = `-- name: ListProductos :many
SELECT id, nombre, descripcion, precio, stock FROM productos ORDER BY nombre
`

func (q *Queries) ListProductos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.Precio,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProducto = `-- name: UpdateProducto :exec
UPDATE productos
SET nombre = $1, descripcion = $2, precio = $3, stock = $4
WHERE id = $5
`

type UpdateProductoParams struct {
	Nombre      string
	Descripcion sql.NullString
	Precio      string
	Stock       int32
	ID          int32
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) error {
	_, err := q.db.ExecContext(ctx, updateProducto,
		arg.Nombre,
		arg.Descripcion,
		arg.Precio,
		arg.Stock,
		arg.ID,
	)
	return err
}
