// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createCategoria = `-- name: CreateCategoria :one
INSERT INTO categoria (id_categoria, nombre, padre_id)
VALUES ($1, $2, $3)
RETURNING id_categoria, nombre, padre_id
`

type CreateCategoriaParams struct {
	IDCategoria int32
	Nombre      string
	PadreID     sql.NullInt32
}

func (q *Queries) CreateCategoria(ctx context.Context, arg CreateCategoriaParams) (Categorium, error) {
	row := q.db.QueryRowContext(ctx, createCategoria, arg.IDCategoria, arg.Nombre, arg.PadreID)
	var i Categorium
	err := row.Scan(&i.IDCategoria, &i.Nombre, &i.PadreID)
	return i, err
}

const createMovimiento = `-- name: CreateMovimiento :one
INSERT INTO movimiento_stock (id_movimiento, producto_id, tipo, cantidad, motivo)
VALUES ($1, $2, $3, $4, $5)
RETURNING id_movimiento, producto_id, tipo, cantidad, motivo, fecha
`

type CreateMovimientoParams struct {
	IDMovimiento int32
	ProductoID   int32
	Tipo         string
	Cantidad     int32
	Motivo       string
}

func (q *Queries) CreateMovimiento(ctx context.Context, arg CreateMovimientoParams) (MovimientoStock, error) {
	row := q.db.QueryRowContext(ctx, createMovimiento,
		arg.IDMovimiento,
		arg.ProductoID,
		arg.Tipo,
		arg.Cantidad,
		arg.Motivo,
	)
	var i MovimientoStock
	err := row.Scan(
		&i.IDMovimiento,
		&i.ProductoID,
		&i.Tipo,
		&i.Cantidad,
		&i.Motivo,
		&i.Fecha,
	)
	return i, err
}

const createProducto = `-- name: CreateProducto :one
INSERT INTO producto (id_producto, nombre, descripcion, precio, stock, id_categoria)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id_producto, nombre, descripcion, precio, stock, id_categoria
`

type CreateProductoParams struct {
	IDProducto  int32
	Nombre      string
	Descripcion sql.NullString
	Precio      string
	Stock       int32
	IDCategoria sql.NullInt32
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, createProducto,
		arg.IDProducto,
		arg.Nombre,
		arg.Descripcion,
		arg.Precio,
		arg.Stock,
		arg.IDCategoria,
	)
	var i Producto
	err := row.Scan(
		&i.IDProducto,
		&i.Nombre,
		&i.Descripcion,
		&i.Precio,
		&i.Stock,
		&i.IDCategoria,
	)
	return i, err
}

const deleteCategoria = `-- name: DeleteCategoria :exec
DELETE FROM categoria 
WHERE id_categoria = $1
`

func (q *Queries) DeleteCategoria(ctx context.Context, idCategoria int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategoria, idCategoria)
	return err
}

const deleteMovimiento = `-- name: DeleteMovimiento :exec
DELETE FROM movimiento_stock 
WHERE id_movimiento = $1
`

func (q *Queries) DeleteMovimiento(ctx context.Context, idMovimiento int32) error {
	_, err := q.db.ExecContext(ctx, deleteMovimiento, idMovimiento)
	return err
}

const deleteProducto = `-- name: DeleteProducto :exec
DELETE FROM producto 
WHERE id_producto = $1
`

func (q *Queries) DeleteProducto(ctx context.Context, idProducto int32) error {
	_, err := q.db.ExecContext(ctx, deleteProducto, idProducto)
	return err
}

const getCategoriaByID = `-- name: GetCategoriaByID :one

SELECT id_categoria, nombre, padre_id FROM categoria 
WHERE id_categoria = $1
`

// ============================================================================
// CATEGORIA
// ============================================================================
func (q *Queries) GetCategoriaByID(ctx context.Context, idCategoria int32) (Categorium, error) {
	row := q.db.QueryRowContext(ctx, getCategoriaByID, idCategoria)
	var i Categorium
	err := row.Scan(&i.IDCategoria, &i.Nombre, &i.PadreID)
	return i, err
}

const getMovimientoByID = `-- name: GetMovimientoByID :one

SELECT id_movimiento, producto_id, tipo, cantidad, motivo, fecha FROM movimiento_stock 
WHERE id_movimiento = $1
`

// ============================================================================
// MOVIMIENTO_STOCK
// ============================================================================
func (q *Queries) GetMovimientoByID(ctx context.Context, idMovimiento int32) (MovimientoStock, error) {
	row := q.db.QueryRowContext(ctx, getMovimientoByID, idMovimiento)
	var i MovimientoStock
	err := row.Scan(
		&i.IDMovimiento,
		&i.ProductoID,
		&i.Tipo,
		&i.Cantidad,
		&i.Motivo,
		&i.Fecha,
	)
	return i, err
}

const getProductoByID = `-- name: GetProductoByID :one

SELECT id_producto, nombre, descripcion, precio, stock, id_categoria FROM producto 
WHERE id_producto = $1
`

// ============================================================================
// PRODUCTO
// ============================================================================
func (q *Queries) GetProductoByID(ctx context.Context, idProducto int32) (Producto, error) {
	row := q.db.QueryRowContext(ctx, getProductoByID, idProducto)
	var i Producto
	err := row.Scan(
		&i.IDProducto,
		&i.Nombre,
		&i.Descripcion,
		&i.Precio,
		&i.Stock,
		&i.IDCategoria,
	)
	return i, err
}

const listCategorias = `-- name: ListCategorias :many
SELECT id_categoria, nombre, padre_id FROM categoria 
ORDER BY nombre
`

func (q *Queries) ListCategorias(ctx context.Context) ([]Categorium, error) {
	rows, err := q.db.QueryContext(ctx, listCategorias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Categorium
	for rows.Next() {
		var i Categorium
		if err := rows.Scan(&i.IDCategoria, &i.Nombre, &i.PadreID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriasRaiz = `-- name: ListCategoriasRaiz :many
SELECT id_categoria, nombre, padre_id FROM categoria 
WHERE padre_id IS NULL 
ORDER BY nombre
`

func (q *Queries) ListCategoriasRaiz(ctx context.Context) ([]Categorium, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriasRaiz)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Categorium
	for rows.Next() {
		var i Categorium
		if err := rows.Scan(&i.IDCategoria, &i.Nombre, &i.PadreID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovimientos = `-- name: ListMovimientos :many
SELECT id_movimiento, producto_id, tipo, cantidad, motivo, fecha FROM movimiento_stock 
ORDER BY fecha DESC
`

func (q *Queries) ListMovimientos(ctx context.Context) ([]MovimientoStock, error) {
	rows, err := q.db.QueryContext(ctx, listMovimientos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovimientoStock
	for rows.Next() {
		var i MovimientoStock
		if err := rows.Scan(
			&i.IDMovimiento,
			&i.ProductoID,
			&i.Tipo,
			&i.Cantidad,
			&i.Motivo,
			&i.Fecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovimientosByProducto = `-- name: ListMovimientosByProducto :many
SELECT id_movimiento, producto_id, tipo, cantidad, motivo, fecha FROM movimiento_stock 
WHERE producto_id = $1 
ORDER BY fecha DESC
`

func (q *Queries) ListMovimientosByProducto(ctx context.Context, productoID int32) ([]MovimientoStock, error) {
	rows, err := q.db.QueryContext(ctx, listMovimientosByProducto, productoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovimientoStock
	for rows.Next() {
		var i MovimientoStock
		if err := rows.Scan(
			&i.IDMovimiento,
			&i.ProductoID,
			&i.Tipo,
			&i.Cantidad,
			&i.Motivo,
			&i.Fecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductos = `-- name: ListProductos :many
SELECT id_producto, nombre, descripcion, precio, stock, id_categoria FROM producto 
ORDER BY nombre
`

func (q *Queries) ListProductos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.IDProducto,
			&i.Nombre,
			&i.Descripcion,
			&i.Precio,
			&i.Stock,
			&i.IDCategoria,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcategorias = `-- name: ListSubcategorias :many
SELECT id_categoria, nombre, padre_id FROM categoria 
WHERE padre_id = $1 
ORDER BY nombre
`

func (q *Queries) ListSubcategorias(ctx context.Context, padreID sql.NullInt32) ([]Categorium, error) {
	rows, err := q.db.QueryContext(ctx, listSubcategorias, padreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Categorium
	for rows.Next() {
		var i Categorium
		if err := rows.Scan(&i.IDCategoria, &i.Nombre, &i.PadreID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoria = `-- name: UpdateCategoria :exec
UPDATE categoria
SET nombre = $1, padre_id = $2
WHERE id_categoria = $3
`

type UpdateCategoriaParams struct {
	Nombre      string
	PadreID     sql.NullInt32
	IDCategoria int32
}

func (q *Queries) UpdateCategoria(ctx context.Context, arg UpdateCategoriaParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoria, arg.Nombre, arg.PadreID, arg.IDCategoria)
	return err
}

const updateProducto = `-- name: UpdateProducto :exec
UPDATE producto
SET nombre = $1, descripcion = $2, precio = $3, stock = $4, id_categoria = $5
WHERE id_producto = $6
`

type UpdateProductoParams struct {
	Nombre      string
	Descripcion sql.NullString
	Precio      string
	Stock       int32
	IDCategoria sql.NullInt32
	IDProducto  int32
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) error {
	_, err := q.db.ExecContext(ctx, updateProducto,
		arg.Nombre,
		arg.Descripcion,
		arg.Precio,
		arg.Stock,
		arg.IDCategoria,
		arg.IDProducto,
	)
	return err
}
